<?php

use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\TestController;
use App\Http\Controllers\SmsController;
use Illuminate\Support\Facades\Route;
use App\Services\PaymentService;


//Facade practics




//Class Fish{
//
//    public function swim(){
//        return "Swiming";
//    }
//    public function eat(){
//        return "eat";
//    }
//
//}
//
//class Bike{
//    public function start(){
//        return "Bike start Succss";
//    }
//}
//app()->bind('Bike', function(){
//   return new Bike();
//});
//app()->bind('Fish', function(){
//    return new Fish();
//});
//
//class Facade{
//    public static function __callStatic(string $name, array $arguments)
//    {
////        dd(self::getAccesors());
//        return app()->make(static::getAccesors())->$name();
//    }
//    protected static function getAccesors(){
//
//    }
//}
//class BikeFacade extends Facade{
//    protected static function getAccesors()
//    {
//        return "Bike"; // TODO: Change the autogenerated stub
//    }
//}
//class FishFacade extends Facade{
//    protected static function getAccesors()
//    {
//        return "Fish";
//    }
//}
//
//dd(BikeFacade::start());
















/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    dd(env('JWT_SECRET'));
//    dd(app()->make('hello'));
    return view('welcome');
});
Route::get('/test', TestController::class);
Route::get('test/payment', function(PaymentService $payment){
    dd($payment->printPayment());
    return app()->make('first_srvice_provider');
});

Route::get('/send-sms', [SmsController::class, 'sendSms']);


